### ISSUE TITLE
Goto keyword

### ISSUE THREAD

**Issue by newtondotcom** [DatamindDev/MoonDumper#2]
hi, i was using your script with a file and i get the following error :           
`throw a 
1:74618: Unexpected symbol. Keyword goto`
so i decided to add this : 
`
        console.log(`prefixexpr: ${tk.Type}`)
        console.log(`prefixexpr: ${tk.Source}`)
` line 683 in node_modules
and it showed : 
`
prefixexpr: Keyword
prefixexpr: goto
<Keyword `goto`> at: 1:74618
`
so i am guessing there is an issue because nor the type nor the source is recognized of the keyword goto

**Comment by DatamindDev** [comment]
If you try to constant dump new obfuscated moonsec v3 scripts its not gonna work since they added some checks.But for the old it only works on max security or constant protection enabled or both. I may make this dumper discountinued due to it getting patched.
